name: ui_common_behaviors
repository: https://github.com/gordianknotC/dart_common_ui_behaviors.git
publish_to: none
description: Common front end ui reactive behaviors implemented on Mobx
# version: 1.0.0
# homepage: https://www.example.com
# author: gordianknot <gordianknot.app@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mobx: ^2.1.3

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.22.2
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  
  