name: ui_common_behaviors
description: Common front end ui reactive behaviors implemented on Mobx
# version: 1.0.0
# homepage: https://www.example.com
# author: gordianknot <gordianknot.app@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  mobx: 1.2.1+4

dev_dependencies:
  pedantic: 1.8.0+1
  test: ^1.6.3
  build_runner: ^1.3.1
  mobx_codegen: 1.1.2
